<h2>Agregar Categoria</h2>
<div class="row">
    <div class="col-sm-6">
        <form action="<?php echo APP_URL.'categorias/agregar'; ?>" method="post">
            <p>
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" class="form-control">
            </p>
            <p>
            <input type="submit" class="btn" value="Guardar categoria"></p>
        </form>
    </div>
    <div class="col-sm-6"></div>
</div>