<div class="row">
    <div class="col-sm-8"><h3>Listado de Categorias</h3></div>
    <div class="col-sm-8">
        <a href="<?php echo APP_URL."tareas/agregar"; ?>">
            <button type="button" class="btn-primary add">
                <span class="glyphicon glyphicon-plus">Tarea</span>
            </button>
        </a>
        <a href="<?php echo APP_URL."categorias/agregar"; ?>">
            <button type="button" class="btn-primary add">
                <span class="glyphicon glyphicon-plus">Categoria</span>
            </button>
        </a>
    </div>
</div>
<div class="table-responsive">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Acción</th>
        </tr>
        <?php foreach ($this->categoria as $categoria): ?>
        <tr>
            <td>
            <?php echo $categoria["categorias"]["id"]; ?>
            </td>
            <td>
                <?php                     echo $categoria["categorias"]["nombre"]; ?>
            </td>
            <td>
                <a href="<?php echo APP_URL."categorias/editar/".$categoria["categorias"]["id"]; ?>">
                    <span class="glyphicon glyphicon-edit"> </span>
                </a>  | 
                <a href="<?php echo APP_URL."categorias/eliminar/".$categoria["categorias"]["id"]; ?>">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
            </td>
        </tr>
    <?php endforeach;?>
    </table>
</div>