<div class="row">
    <div class="col-sm-8"><p>  </p></div>
    <div class="col-sm-8">
        <a href="<?php echo APP_URL."tareas/agregar"; ?>" class="waves-effect waves-light btn">
            <i class="material-icons left">add</i>Tarea
        </a>

        <a href="<?php echo APP_URL."categorias/agregar"; ?>" class="waves-effect waves-light btn">
            <i class="material-icons left">add</i>Categoria
        </a>
        
    </div>
</div>
<div class="table-responsive">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Acción</th>
        </tr>
        <?php foreach ($this->categoria as $categoria): ?>
        <tr>
            <td>
            <?php echo $categoria["categorias"]["id"]; ?>
            </td>
            <td>
                <?php echo $categoria["categorias"]["nombre"]; ?>
            </td>
            <td>
                <a href="<?php echo APP_URL."categorias/editar/".$categoria["categorias"]["id"]; ?>">
                    <i class="material-icons left">border_color</i>
                </a>
                <a href="<?php echo APP_URL."categorias/eliminar/".$categoria["categorias"]["id"]; ?>">
                    <i class="material-icons left">delete</i>
                </a>
            </td>
        </tr>
    <?php endforeach;?>
    </table>
</div>