<div class="row">
    <div class="col-sm-8"><p>  </p></div>
    <div class="col-sm-8">
        <a href="<?php echo APP_URL."tareas/agregar"; ?>" class="waves-effect waves-light btn">
            <i class="material-icons left">add</i>Tarea
        </a>

        <a href="<?php echo APP_URL."categorias/agregar"; ?>" class="waves-effect waves-light btn">
            <i class="material-icons left">add</i>Categoria
        </a>
        
    </div>
</div>
    <div>
        <table class="striped centered responsive-table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Fecha</th>
                    <th>Prioridad</th>
                    <th>Categoria</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->tareas as $tarea): ?>
                <tr>
                    <td><?php echo $tarea["tareas"]["id"]; ?></td>
                    <td>
                        <?php
                            if ($tarea["tareas"]["status"]==0):
                                echo "<s>".$tarea["tareas"]["nombre"]."</s>";
                            else:
                                echo $tarea["tareas"]["nombre"];
                            endif;
                        ?>
                    </td>
                    <td><?php
                        $date = date_create($tarea["tareas"]["fecha"]);
                        echo date_format($date, 'd/m/Y'); 
                        ?>
                    </td>
                    <td>
                        <?php
                            if ($tarea["tareas"]["prioridad"]<=3) {
                                echo '<span class="white-text badge green">Baja&nbsp;&nbsp;&nbsp;</span>';
                            }elseif ($tarea["tareas"]["prioridad"]<=6) {
                                echo '<span class="white-text badge orange">Media&nbsp;&nbsp;&nbsp;</span>';
                            }elseif ($tarea["tareas"]["prioridad"]) {
                                echo '<span class="white-text badge red">Alta&nbsp;&nbsp;&nbsp;</span>';
                            }   
                        ?>
                    </td>
                    <td><?php echo $tarea["categorias"]["nombre"];?></td>
                    <td>
                        <a href="<?php echo APP_URL."tareas/editar/".$tarea["tareas"]["id"]; ?>">
                            <i class="material-icons left">border_color</i>
                        </a>
                        <a href="<?php echo APP_URL."tareas/eliminar/".$tarea["tareas"]["id"]; ?>">
                            <i class="material-icons left">delete</i>
                        </a>
                        <?php
                        if ($tarea["tareas"]["status"]==1) {?>
                            <a href="<?php echo APP_URL."tareas/cambiarEstado/".$tarea["tareas"]["id"]."/off"; ?>">
                                <i class="material-icons left">check</i>
                            </a>
                        <?php }elseif($tarea["tareas"]["status"]==0) {?>
                            <a href="<?php echo APP_URL."tareas/cambiarEstado/".$tarea["tareas"]["id"]."/on"; ?>">
                                <i class="material-icons left">close</i>
                            </a>
                        <?php } ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>